import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next crash course with sumit saha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"   className="p-8 bg-slate-500">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex gap-6">
            <li> <Link href="/">Home</Link></li>
            <li> <Link href="/about">About</Link></li>
            <li> <Link href="/">Services</Link></li>

          </ul>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
